export const CREATE_USER = 'CREATE_USER';
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
export const DELETE_USER = 'DELETE_USER';

export const ADD_CARD = 'ADD_CARD';
export const MOVE_CARD = 'MOVE_CARD';

export const SET_DRAGGING_ACTIVE = 'SET_DRAGGING_ACTIVE';
export const SET_DRAGGING_INACTIVE = 'SET_DRAGGING_INACTIVE';
export const SET_DRAGGING_CARD_ID = 'SET_DRAGGING_CARD_ID';
export const SET_CARD_DESTINATION = 'SET_CARD_DESTINATION';

export const ADD_COLUMN = 'ADD_COLUMN';
